version: 2
jobs:
  dependencies:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-modules-cache-{{ .Branch }}-{{ checksum "package.json" }}
      - run: yarn
      - save_cache:
          key: node-modules-cache-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ./node_modules
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-modules-cache-{{ .Branch }}-{{ checksum "package.json" }}
      - run: yarn build
  test:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-modules-cache-{{ .Branch }}-{{ checksum "package.json" }}
      - run: yarn test
  deploy:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: scp -r react-quick-start/build/* circleci@45.32.116.46:/usr/share/nginx/reactjs.blogcuaviet.com/html

workflows:
  version: 2
  build_test_deploy:
    jobs:
    - dependencies
    - build:
        requires:
          - dependencies
    - test:
        requires:
          - dependencies
    - deploy:
        requires:
          - build
          - test
