version: 2
jobs:
  dependencies:
    docker:
      - image: circleci/node
    working_directory: ~/react-quick-start
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-modules-cache-{{ .Branch }}-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: node-modules-cache-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - node_modules
  test:
    docker:
      - image: circleci/node
    working_directory: ~/react-quick-start
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-modules-cache-{{ .Branch }}-{{ checksum "package.json" }}
      - run: npm run test
  build_deploy:
    docker:
      - image: circleci/node
    working_directory: ~/react-quick-start
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-modules-cache-{{ .Branch }}-{{ checksum "package.json" }}
      - add_ssh_keys:
          fingerprints:
            - 'd3:9b:a7:42:1f:e1:71:8b:c0:cf:b6:60:3b:26:95:2b'
      - run: npm run build
      - run: ssh-keyscan $SERVER_IP >> ~/.ssh/known_hosts
      - run: ssh $USER@$SERVER_IP 'rm -rf *'
      - run: scp -r build/* $USER@$SERVER_IP:.

workflows:
  version: 2
  test_build_deploy:
    jobs:
      - dependencies
      - test:
          requires:
            - dependencies
      - build_deploy:
          requires:
            - test
