version: 2
jobs:
  dependencies:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-modules-cache-{{ .Branch }}-{{ checksum "package.json" }}
      - run: yarn
      - save_cache:
          key: node-modules-cache-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ./node_modules
  test:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-modules-cache-{{ .Branch }}-{{ checksum "package.json" }}
      - run: yarn test
  build_deploy:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-modules-cache-{{ .Branch }}-{{ checksum "package.json" }}
      - run: yarn build
      - run: scp -o StrictHostKeyChecking=no -r ~/project/react-quick-start/build/* circleci@45.32.116.46:/usr/share/nginx/reactjs.blogcuaviet.com/html

workflows:
  version: 2
  test_build_deploy:
    jobs:
    - dependencies
    - test:
        requires:
          - dependencies
    - build_deploy:
        requires:
          - dependencies
          - test
