version: 2
jobs:
  dependencies:
    docker:
      - image: circleci/node:latest
    working_directory: ~/react-quick-start
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-modules-cache-{{ .Branch }}-{{ checksum "package.json" }}
      - run: yarn
      - save_cache:
          key: node-modules-cache-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - node_modules
  test:
    docker:
      - image: circleci/node:latest
    working_directory: ~/react-quick-start
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-modules-cache-{{ .Branch }}-{{ checksum "package.json" }}
      - run: yarn test
  build_deploy:
    docker:
      - image: circleci/node:latest
    working_directory: ~/react-quick-start
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-modules-cache-{{ .Branch }}-{{ checksum "package.json" }}
      - run: yarn build
      - run: ssh circleci@45.32.116.46 'rm -rf /usr/share/nginx/reactjs.blogcuaviet.com/html/*'
      - run: ssh-keyscan 45.32.116.46 >> ~/.ssh/known_hosts
      - run: scp -r build/* circleci@45.32.116.46:/usr/share/nginx/reactjs.blogcuaviet.com/html

workflows:
  version: 2
  test_build_deploy:
    jobs:
    - dependencies
    - test:
        requires:
          - dependencies
    - build_deploy:
        requires:
          - test
